version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"


  hercai:
    build:
      context: ./hercai
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend