# Generated by Django 4.2.7 on 2023-11-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='turma',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
