# Generated by Django 4.2.7 on 2023-11-24 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date published')),
            ],
        ),
    ]
