# Generated by Django 4.2.7 on 2023-11-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
