# Generated by Django 4.2.7 on 2023-11-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='choice',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='historic',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
