# Generated by Django 4.2.7 on 2023-11-24 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date',
            field=models.DateTimeField(blank=None, default=django.utils.timezone.now, null=True, verbose_name='date published'),
        ),
    ]
