# Generated by Django 4.2.7 on 2023-11-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_image_nome'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
            ],
        ),
    ]
