# Generated by Django 4.2.7 on 2023-11-25 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('app', '0002_alter_function_description_alter_function_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='icon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
