# Generated by Django 4.2.7 on 2023-11-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': 'KeyWord', 'verbose_name_plural': 'KeyWords'},
        ),
    ]
