# Generated by Django 4.2.7 on 2023-11-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_keywords_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='ai',
            field=models.IntegerField(choices=[(1, 'GPT'), (2, 'Llama')], default=1),
        ),
    ]
