# Generated by Django 4.2.7 on 2023-11-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ai_favorite_function_historic_remove_question_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='ai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ai'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.function'),
        ),
    ]
