# Generated by Django 4.2.7 on 2023-11-24 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_alter_historic_ai_alter_historic_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default=None, max_length=200)),
                ('choice', models.CharField(default=None, max_length=200)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date published')),
                ('ai', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.ai')),
                ('chat', models.ManyToManyField(default=None, related_name='chat_history', to='app.chat')),
                ('function', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.function')),
            ],
        ),
    ]
