# Generated by Django 4.2.7 on 2023-11-25 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuario_data_nascimento'),
        ('usuario', '0003_usuario_password_reset_token_and_more'),
    ]

    operations = [
    ]
