# Generated by Django 4.2.7 on 2023-11-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Birth'),
        ),
    ]
