# Generated by Django 4.2.7 on 2023-11-25 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_merge_20231125_0230'),
        ('usuario', '0004_usuario_birth'),
    ]

    operations = [
    ]
