# Generated by Django 4.2.7 on 2023-11-25 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('usuario', '0005_merge_0004_merge_20231125_0230_0004_usuario_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
